### PR TITLE
Render PDF with GitHub actions

### PR DESCRIPTION
**Pull request by nrennie**
- Have fixed the references issue. (Currently has duplicate reference list since the manual list is still in docs/references.qmd)
- I've run {styler} on the code blocks and I think most of them fit on the page now
- Added very minimal styling to PDF (but set up is there for added customisation)
- Adds GH action to render PDF and push to main (this could be deployed elsewhere if needed, but for now we can link to the GH file). This won't run until after the PR is merged into main (if it fails, let me know)
- Before merging, can you make sure that in Settings → Actions → workflow permissions are set to read and write (so that the rendered PDF can be saved).

Should be merged after #12

### CODE REVIEW

**Comment by brtarran** [comment]
Thanks for these, @nrennie. Couple of comments/questions:
- Are you able to set RSS logo to bottom left on the PDF?
- In the PDF, the reference list is duplicated, as you say, because we still have the manual list in the references.qmd file. But I can't see a way to remove the manual list and have the references.qmd pull all the bibtext references from across the site into one web page, as it does with the PDF. Do you know of a way to do this?
- Any easy way to exclude our bio photos from the PDF, or at least make sure they are properly paired with the relevant text?
- Read/write permissions set, as requested.

**Comment by nrennie** [comment]
Yes, I'll push commits where:

- I've moved the RSS logo to the left
- I've used the `nocite` option which will create a list of all references in the .bib file and added this to the existing references on the references page, so we have a complete list. I've removed the manual reference list.
- I've added `suppress-bibliography: true` to the individual pages to stop the full references list appearing on every page.
- Author photos are hidden if output format is PDF

**Comment by brtarran** [comment]
PDF looks good. Fixed error where the `.content-include` was forcing bio images to display as small thumbnails on the web version. Tested on PDF as still working as intended.

`nocite` and `suppress-bibliography` create new problems, however. Hover-over ref pop-ups in individual pages are now empty. I know we can disable the hover-over pop-ups, but I quite like that functionality.

Any ideas? Or is it a case of pick one option:

- Full bibtext ref list at end; or
- Pop-up ref links throughout?

**Comment by nrennie** [comment]
This seems to be caused by `suppress-bibliography` rather than `nocite`. One option could be to put the full references on every page (so hover pop-ups still work), but to put them in a collapsed section at the bottom so they're hidden?

**Comment by brtarran** [comment]
Solution was more straightforward than I thought: `nocite` removed from global settings to just the refs page, and `suppress-bibliography` removed from all other pages. So, now each page has a reference list and active links + a full reference list online, while PDF just has the full reference list at the end because `nocite` still global in the _make_pdf.qmd YAML.

**Review by brtarran — APPROVED** [review]

**Pull request merged**
